kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: regional
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: regional-pd
allowVolumeExpansion: true
---
apiVersion: v1
kind: Service
metadata:
  name: private-node
  labels:
    app: private-node
spec:
  ports:
  - port: 9933
    name: rpc
  - port: 9615
    name: metrics
  selector:
    app: private-node
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: private-node-p2p
  labels:
    app: private-node
  annotations:
    cloud.google.com/network-tier: Standard
spec:
  selector:
    app: private-node
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: private-node
    release: monitoring
  name: private-monitoring
spec:
  endpoints:
  - interval: 15s
    port: metrics
    path: /metrics
  selector:
    matchLabels:
      app: private-node
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: polkadot-private-node-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: private-node
  policyTypes:
  - Ingress
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 443
      protocol: TCP
    - port: 30333
      protocol: TCP
    - port: 30334
      protocol: TCP
    - port: 30100
      protocol: TCP
  ingress:
  - ports:
    - port: 30333
      protocol: TCP
  - ports:
    - port: 9615
      protocol: TCP
    from:
    - namespaceSelector:
        matchLabels: {}
      podSelector:
        matchLabels:
          app: prometheus
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: private-node
spec:
  selector:
    matchLabels:
      app: private-node
  serviceName: private-node
  replicas: 1
  template:
    metadata:
      labels:
        app: private-node
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: polkadot-private-node
        image: polkadot-private-node
        ports:
        - containerPort: 9933
          name: dot-rpc-port
        - containerPort: 9615
          name: metrics
        - containerPort: 30333
          name: dot-p2p-port
        volumeMounts:
        - name: polkadot-private-node-pv-claim
          mountPath: /polkadot
        envFrom:
        - configMapRef:
            name: polkadot-configmap
        resources:
          limits:
            cpu: 0
        imagePullPolicy: Always
      volumes:
      - name: polkadot-node-keys
        secret:
          secretName: polkadot-node-keys
      initContainers:
      - name: polkadot-node-key-configurator
        image: polkadot-node-key-configurator
        volumeMounts:
        - name: polkadot-private-node-pv-claim
          mountPath: /polkadot
        - name: polkadot-node-keys
          mountPath: /polkadot-node-keys
        envFrom:
        - configMapRef:
            name: polkadot-configmap
        imagePullPolicy: Always
      - name: polkadot-archive-downloader
        image: polkadot-archive-downloader
        volumeMounts:
        - name: polkadot-private-node-pv-claim
          mountPath: /polkadot
        env:
        - name: CHAIN
          valueFrom:
            configMapKeyRef:
              name: polkadot-configmap
              key: CHAIN
        - name: ARCHIVE_URL
          valueFrom:
            configMapKeyRef:
              name: polkadot-configmap
              key: ARCHIVE_URL
        imagePullPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: polkadot-private-node-pv-claim
